# 07

## 7.1 自動車の停止距離

## 7.2 データの確認

In [ ]:
import statsmodels.api as sm
my_data = sm.datasets.get_rdataset('cars', 'datasets').data

In [ ]:
my_data.shape
#> (50, 2)

In [ ]:
my_data.head()
#>    speed  dist
#> 0      4     2
#> 1      4    10
#> 2      7     4
#> 3      7    22
#> 4      8    16

In [ ]:
my_data.describe()
#>            speed        dist
#> count  50.000000   50.000000
#> mean   15.400000   42.980000
#> std     5.287644   25.769377
#> min     4.000000    2.000000
#> 25%    12.000000   26.000000
#> 50%    15.000000   36.000000
#> 75%    19.000000   56.000000
#> max    25.000000  120.000000

In [ ]:
my_data.plot(x='speed', style='o')

## 7.3 回帰分析

### 7.3.1 回帰分析とは何か

### 7.3.2 線形単回帰分析

In [ ]:
import seaborn as sns
import statsmodels.api as sm

my_data = sm.datasets.get_rdataset('cars', 'datasets').data
ax = sns.regplot(x='speed', y='dist', data=my_data)
ax.vlines(x=21.5, ymin=-5, ymax=67,   linestyles='dotted')
ax.hlines(y=67,   xmin=4,  xmax=21.5, linestyles='dotted')
ax.set_xlim(4, 25)
ax.set_ylim(-5, 125)

### 7.3.3 回帰分析の実践

#### 7.3.3.1 データの用意

In [ ]:
import statsmodels.api as sm
my_data = sm.datasets.get_rdataset('cars', 'datasets').data
X, y = my_data[['speed']], my_data['dist']

#### 7.3.3.2 訓練

In [ ]:
# モデルの指定
from sklearn.linear_model import LinearRegression
my_model = LinearRegression()

# 訓練（モデルをデータにフィットさせる．）
my_model.fit(X, y)

# まとめて実行してもよい．
# my_model = LinearRegression().fit(X, y)

In [ ]:
my_model.intercept_, my_model.coef_
#> (-17.579094890510973,
#>  array([3.93240876]))

#### 7.3.3.3 予測

In [ ]:
tmp = [[21.5]]
my_model.predict(tmp)
#> array([66.96769343])

#### 7.3.3.4 モデルの可視化

In [ ]:
import numpy as np
import pandas as pd

tmp = pd.DataFrame({'speed': np.linspace(min(my_data.speed),
                                         max(my_data.speed),
                                         100)})
tmp['model'] = my_model.predict(tmp)

In [ ]:
pd.concat([my_data, tmp]).plot(
    x='speed', style=['o', '-'])

## 7.4 当てはまりの良さの指標

### 7.4.1 RMSE

In [ ]:
import pandas as pd
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

my_data = sm.datasets.get_rdataset('cars', 'datasets').data
X, y = my_data[['speed']], my_data['dist']

my_model = LinearRegression()
my_model.fit(X, y)
y_ = my_model.predict(X)
my_data['y_'] = y_

In [ ]:
pd.options.display.float_format = (
    '{:.2f}'.format)
my_data['residual'] = y - y_
my_data.head()
#>    speed  dist    y_  residual
#> 0      4     2 -1.85      3.85
#> 1      4    10 -1.85     11.85
#> 2      7     4  9.95     -5.95
#> 3      7    22  9.95     12.05
#> 4      8    16 13.88      2.12

In [ ]:
ax = my_data.plot(x='speed', y='dist', style='o', legend=False)
my_data.plot(x='speed', y='y_', style='-', legend=False, ax=ax)
ax.vlines(x=X, ymin=y, ymax=y_, linestyles='dotted')

In [ ]:
mean_squared_error(y, y_)**0.5
# あるいは
(my_data['residual']**2).mean()**0.5

#> 15.068855995791381

### 7.4.2 決定係数

In [ ]:
my_model.score(X, y)
# あるいは
r2_score(y_true=y, y_pred=y_)
#> 0.6510793807582509

In [ ]:
import numpy as np
np.corrcoef(y, y_)[0, 1]**2
#> 0.6510793807582511

In [ ]:
my_test = my_data[:3]
X = my_test[['speed']]
y = my_test['dist']
y_ = my_model.predict(X)

my_model.score(X, y)
# あるいは
r2_score(y_true=y, y_pred=y_)
#> -4.498191310376778 # 決定係数1

np.corrcoef(y, y_)[0, 1]**2
#> 0.0769230769230769 # 決定係数6

### 7.4.3 当てはまりの良さの指標の問題点

In [ ]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

my_data = sm.datasets.get_rdataset('cars', 'datasets').data

my_idx = [1, 10, 26, 33, 38, 43]
my_sample = my_data.iloc[my_idx, ]
X, y = my_sample[['speed']], my_sample['dist']

In [ ]:
d = 5
X5 = PolynomialFeatures(d).fit_transform(X) # Xの1乗から5乗の変数

my_model = LinearRegression()
my_model.fit(X5, y)
y_ = my_model.predict(X5)

In [ ]:
((y - y_)**2).mean()**0.5
#> 7.725744805546204e-07 # RMSE

my_model.score(X5, y)
#> 0.9999999999999989 # 決定係数1

np.corrcoef(y, y_)[0, 1]**2
#> 0.9999999999999991 # 決定係数6

In [ ]:
tmp = pd.DataFrame({'speed': np.linspace(min(my_data.speed),
                                         max(my_data.speed),
                                         100)})
X5 = PolynomialFeatures(d).fit_transform(tmp)
tmp['model'] = my_model.predict(X5)

my_sample = my_sample.assign(sample=y)
my_df = pd.concat([my_data, my_sample, tmp])
my_df.plot(x='speed', style=['o', 'o', '-'], ylim=(0, 130))

## 7.5 K最近傍法

### 7.5.1 K最近傍法とは何か

### 7.5.2 K最近傍法の実践

In [ ]:
# 準備
import numpy as np
import pandas as pd
import statsmodels.api as sm
from sklearn.neighbors import KNeighborsRegressor

my_data = sm.datasets.get_rdataset('cars', 'datasets').data
X, y = my_data[['speed']], my_data['dist']

# 訓練
my_model = KNeighborsRegressor()
my_model.fit(X, y)

# 可視化の準備
tmp = pd.DataFrame({'speed': np.linspace(min(my_data.speed),
                                         max(my_data.speed),
                                         100)})
tmp['model'] = my_model.predict(tmp)

In [ ]:
pd.concat([my_data, tmp]).plot(
    x='speed', style=['o', '-'])

In [ ]:
y_ = my_model.predict(X)

((y - y_)**2).mean()**0.5
#> 13.087184571174962 # RMSE

my_model.score(X, y)
#> 0.7368165812204317 # 決定係数1

np.corrcoef(y, y_)[0, 1]**2
#> 0.7380949412509705 # 決定係数6

## 7.6 検証

### 7.6.1 訓練データ・検証データ・テストデータ

### 7.6.2 検証とは何か

### 7.6.3 検証の実践

In [ ]:
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

# データの準備
my_data = sm.datasets.get_rdataset('cars', 'datasets').data
X, y = my_data[['speed']], my_data['dist']

# モデルの指定
my_model = LinearRegression()

# 検証（5分割交差検証）
my_scores = cross_val_score(my_model, X, y)

# 5個の決定係数1を得る．
my_scores
#> array([-0.25789256, -0.21421069, -0.30902773, -0.27346232,  0.02312918])

# 平均を決定係数1（検証）とする．
my_scores.mean()
#> -0.20629282165364665

In [ ]:
my_scores = cross_val_score(my_model, X, y,
                            scoring='neg_root_mean_squared_error')
-my_scores.mean()
#> 15.58402474583013 # RMSE（検証）

### 7.6.4 検証の並列化

### 7.6.5 指標のまとめ

#### 7.6.5.1 準備

In [ ]:
import numpy as np
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import cross_val_score, LeaveOneOut

my_data = sm.datasets.get_rdataset('cars', 'datasets').data
X, y = my_data[['speed']], my_data['dist']
my_model = LinearRegression().fit(X, y)
y_ = my_model.predict(X)

#### 7.6.5.2 当てはまりの良さの指標

In [ ]:
# RMSE（訓練）
mean_squared_error(y, y_)**0.5
#> 15.068855995791381

# 決定係数1（訓練）
my_model.score(X, y)
# あるいは
r2_score(y_true=y, y_pred=y_)
#> 0.6510793807582509

# 決定係数6（訓練）
np.corrcoef(y, y_)[0, 1]**2
#> 0.6510793807582511

#### 7.6.5.3 予測性能の指標（簡単に求められるもの）

In [ ]:
my_scores = cross_val_score(my_model, X, y,
                            scoring='neg_root_mean_squared_error')
-my_scores.mean()
#> 15.301860331378464  # RMSE（検証）

my_scores = cross_val_score(my_model, X, y, scoring='r2') # scoring='r2'は省略可
my_scores.mean()
#> 0.49061365458235245 # 決定係数1（検証）

#### 7.6.5.4 予測性能の指標（RとPythonで同じ結果を得る）

In [ ]:
# 方法1
my_scores1 = cross_val_score(my_model, X, y, cv=LeaveOneOut(),
                             scoring='neg_mean_squared_error')
(-my_scores1.mean())**0.5
#> 15.697306009399101

# 方法2
my_scores2 = cross_val_score(my_model, X, y, cv=LeaveOneOut(),
                             scoring='neg_root_mean_squared_error')
(my_scores2**2).mean()**0.5
#> 15.697306009399101

In [ ]:
-my_scores2.mean()
#> 12.059178648637483

### 7.6.6 補足：検証による手法の比較

In [ ]:
import pandas as pd
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score, LeaveOneOut
from sklearn.neighbors import KNeighborsRegressor

my_data = sm.datasets.get_rdataset('cars', 'datasets').data
X, y = my_data[['speed']], my_data['dist']

my_lm_scores = cross_val_score(
    LinearRegression(),
    X, y, cv=LeaveOneOut(), scoring='neg_mean_squared_error')

my_knn_socres = cross_val_score(
    KNeighborsRegressor(n_neighbors=5),
    X, y, cv=LeaveOneOut(), scoring='neg_mean_squared_error')

In [ ]:
(-my_lm_scores.mean())**0.5
#> 15.697306009399101 # 線形回帰分析

(-my_knn_socres.mean())**0.5
#> 16.07308308943869 # K最近傍法

In [ ]:
my_df = pd.DataFrame({
    'lm': -my_lm_scores,
    'knn': -my_knn_socres})
my_df.head()
#>            lm     knn
#> 0   18.913720  108.16
#> 1  179.215044    0.64
#> 2   41.034336   64.00
#> 3  168.490212  184.96
#> 4    5.085308    0.00

In [ ]:
my_df.boxplot().set_ylabel("$r^2$")

In [ ]:
from statsmodels.stats.weightstats import DescrStatsW
d = DescrStatsW(my_df.lm - my_df.knn)
d.ttest_mean()[1] # p値
#> 0.6952755720536115

d.tconfint_mean(alpha=0.05, alternative='two-sided') # 信頼区間
#> (-72.8275283312228, 48.95036023665703)

## 7.7 パラメータチューニング

In [ ]:
import pandas as pd
import statsmodels.api as sm
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV, LeaveOneOut
from sklearn.neighbors import KNeighborsRegressor

my_data = sm.datasets.get_rdataset('cars', 'datasets').data
X, y = my_data[['speed']], my_data['dist']

my_params = {'n_neighbors': range(1, 16)} # 探索範囲（1以上16未満の整数）

my_search = GridSearchCV(estimator=KNeighborsRegressor(),
                         param_grid=my_params,
                         cv=LeaveOneOut(),
                         scoring='neg_mean_squared_error')
my_search.fit(X, y)

In [ ]:
tmp = my_search.cv_results_                # チューニングの詳細
my_scores = (-tmp['mean_test_score'])**0.5 # RMSE
my_results = pd.DataFrame(tmp['params']).assign(validation=my_scores)

In [ ]:
my_results.head()
#>    n_neighbors  validation
#> 0            1   20.089798
#> 1            2   17.577685
#> 2            3   16.348836
#> 3            4   16.198804
#> 4            5   16.073083

In [ ]:
my_results.plot(x='n_neighbors',
                style='o-',
                ylabel='RMSE')

In [ ]:
my_search.best_params_
#> {'n_neighbors': 5}

In [ ]:
(-my_search.best_score_)**0.5
#> 16.07308308943869

In [ ]:
my_model = my_search.best_estimator_
y_ = my_model.predict(X)
mean_squared_error(y_, y)**0.5
#> 13.087184571174962

### 7.7.1 補足：ハイパーパラメータとRMSE（訓練）

In [ ]:
import pandas as pd
import statsmodels.api as sm
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score, LeaveOneOut
from sklearn.neighbors import KNeighborsRegressor

my_data = sm.datasets.get_rdataset('cars', 'datasets').data
X, y = my_data[['speed']], my_data['dist']

def my_loocv(k):
    my_model = KNeighborsRegressor(n_neighbors=k)
    my_scores = cross_val_score(estimator=my_model, X=X, y=y,
                                cv=LeaveOneOut(),
                                scoring='neg_mean_squared_error')
    y_ = my_model.fit(X, y).predict(X)
    return pd.Series([k,
                      (-my_scores.mean())**0.5,        # RMSE（検証）
                      mean_squared_error(y_, y)**0.5], # RMSE（訓練）
                     index=['n_neighbors', 'validation', 'training'])

my_results = pd.Series(range(1, 16)).apply(my_loocv)

In [ ]:
my_results.plot(x='n_neighbors',
                style='o-',
                ylabel='RMSE')